import { GameWord } from '../models';

// Full vocabulary lists for each CEFR level
export const vocabularyLists: Record<string, GameWord[]> = {
  A1: [
    {
      id: 'a1_1',
      word: 'apple',
      definition:
        'A round fruit with red, yellow, or green skin and a white flesh',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_2',
      word: 'house',
      definition: 'A building where people live',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_3',
      word: 'book',
      definition: 'A set of printed pages bound together inside a cover',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_4',
      word: 'water',
      definition:
        'A colorless, transparent liquid that forms the seas, lakes, rivers, and rain',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_5',
      word: 'chair',
      definition:
        'A separate seat for one person, typically with a back and four legs',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_6',
      word: 'table',
      definition:
        'A piece of furniture with a flat top supported by one or more legs',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_7',
      word: 'friend',
      definition:
        'A person you know well and like, but who is not related to you',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_8',
      word: 'family',
      definition: 'A group of people who are related to each other',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_9',
      word: 'school',
      definition: 'A place where children go to be educated',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_10',
      word: 'food',
      definition: 'Things that people or animals eat',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_11',
      word: 'drink',
      definition: 'A liquid that people consume',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_12',
      word: 'car',
      definition: 'A road vehicle with an engine, four wheels, and seats',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_13',
      word: 'bus',
      definition: 'A large vehicle that carries passengers by road',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_14',
      word: 'train',
      definition: 'A connected series of vehicles that runs on railways',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_15',
      word: 'day',
      definition: 'A period of 24 hours',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_16',
      word: 'night',
      definition: 'The dark period between sunset and sunrise',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_17',
      word: 'time',
      definition: 'What we measure in hours, minutes, and seconds',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_18',
      word: 'money',
      definition: 'Coins or paper used to buy things',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_19',
      word: 'shop',
      definition: 'A place where you can buy things',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_20',
      word: 'phone',
      definition: 'A device used for talking to someone who is far away',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_21',
      word: 'banana',
      definition: 'A long curved fruit with a yellow skin',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_22',
      word: 'beach',
      definition: 'An area of sand or small stones beside the sea or a lake',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_23',
      word: 'brother',
      definition: 'A male who has the same parents as another person',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_24',
      word: 'doctor',
      definition: 'A person qualified to treat people who are ill',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_25',
      word: 'hotel',
      definition: 'A place providing accommodation and meals for travelers',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_26',
      word: 'music',
      definition: 'Sounds made by singing or by playing instruments',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_27',
      word: 'sister',
      definition: 'A female who has the same parents as another person',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_28',
      word: 'student',
      definition: 'A person who is studying at a school or university',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_29',
      word: 'window',
      definition: 'An opening in a wall or vehicle with glass to see through',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_30',
      word: 'teacher',
      definition: 'A person who helps students to learn',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_31',
      word: 'animal',
      definition: 'A living organism that feeds on organic matter',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_32',
      word: 'answer',
      definition: 'A response to a question or situation',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_33',
      word: 'bicycle',
      definition: 'A vehicle with two wheels propelled by pedals',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_34',
      word: 'breakfast',
      definition: 'The first meal of the day, typically eaten in the morning',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_35',
      word: 'camera',
      definition:
        'A device for recording visual images in the form of photographs or videos',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_36',
      word: 'child',
      definition: 'A young human being below the age of puberty',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_37',
      word: 'dinner',
      definition: 'The main meal of the day, typically eaten in the evening',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_38',
      word: 'father',
      definition: 'A male parent in relation to his child or children',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_39',
      word: 'garden',
      definition:
        'A piece of ground used for growing flowers, fruit, or vegetables',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_40',
      word: 'kitchen',
      definition: 'A room where food is prepared and cooked',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_41',
      word: 'mother',
      definition: 'A female parent',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_42',
      word: 'orange',
      definition:
        'A round juicy citrus fruit with a tough bright reddish-yellow rind',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_43',
      word: 'park',
      definition: 'A large public garden or area of land used for recreation',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_44',
      word: 'pencil',
      definition:
        'An instrument for writing or drawing, consisting of a thin stick of graphite',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_45',
      word: 'picture',
      definition: 'A painting, drawing, or photograph',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_46',
      word: 'restaurant',
      definition: 'A place where people pay to sit and eat meals',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_47',
      word: 'ruler',
      definition:
        'A straight strip or stick, typically marked with units for measuring',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_48',
      word: 'street',
      definition:
        'A public road in a city, town, or village, typically with houses on each side',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_49',
      word: 'shirt',
      definition:
        'A garment for the upper body made of fabric, with a collar and sleeves',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_50',
      word: 'television',
      definition:
        'A device that receives broadcast signals and displays them on a screen',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_51',
      word: 'baby',
      definition: 'A very young child',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_52',
      word: 'bag',
      definition:
        'A container made of flexible material with an opening at the top',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_53',
      word: 'ball',
      definition: 'A round object used in games and sports',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_54',
      word: 'birthday',
      definition: 'The anniversary of the day on which a person was born',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_55',
      word: 'board',
      definition: 'A long, thin, flat piece of wood or other hard material',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_56',
      word: 'clock',
      definition: 'A mechanical or electrical device for measuring time',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_57',
      word: 'computer',
      definition: 'An electronic device for storing and processing data',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_58',
      word: 'country',
      definition: 'A nation with its own government and territory',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_59',
      word: 'date',
      definition: 'A particular day of the month or year',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_60',
      word: 'desk',
      definition:
        'A piece of furniture with a flat or sloped surface for writing or reading',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_61',
      word: 'door',
      definition:
        'A hinged, sliding, or revolving barrier at the entrance to a building or room',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_62',
      word: 'email',
      definition: 'Messages sent electronically from one computer to another',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_63',
      word: 'evening',
      definition: 'The period of time at the end of the day when it gets dark',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_64',
      word: 'exam',
      definition: 'A formal test of knowledge or proficiency',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_65',
      word: 'floor',
      definition: 'The lower surface of a room on which one stands',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_66',
      word: 'fruit',
      definition:
        'The sweet and fleshy product of a tree or plant that contains seeds',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_67',
      word: 'game',
      definition: 'An activity that one engages in for amusement or fun',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_68',
      word: 'girl',
      definition: 'A female child',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_69',
      word: 'glass',
      definition:
        'A hard, transparent material used for windows and drinking containers',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_70',
      word: 'hand',
      definition: "The end part of a person's arm beyond the wrist",
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_71',
      word: 'head',
      definition:
        'The upper part of the human body containing the brain and facial features',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_72',
      word: 'hour',
      definition: 'A period of time equal to 60 minutes',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_73',
      word: 'husband',
      definition: 'A married man considered in relation to his spouse',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_74',
      word: 'key',
      definition: 'A small piece of metal used to open or lock a door',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_75',
      word: 'lunch',
      definition: 'A meal eaten in the middle of the day',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_76',
      word: 'map',
      definition: 'A diagrammatic representation of an area of land or sea',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_77',
      word: 'morning',
      definition: 'The early part of the day before noon',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_78',
      word: 'name',
      definition:
        'A word or words by which a person, animal, place, or thing is known',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_79',
      word: 'number',
      definition: 'A mathematical value expressed by a word, symbol, or figure',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_80',
      word: 'office',
      definition: 'A room, set of rooms, or building used as a place for work',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_61',
      word: 'paper',
      definition:
        'Material manufactured in thin sheets from the pulp of wood or other fibrous substances, used for writing, drawing, printing, or other purposes',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_62',
      word: 'pencil',
      definition:
        'An instrument for writing or drawing, consisting of a thin stick of graphite enclosed in a long thin piece of wood',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_63',
      word: 'people',
      definition: 'Human beings in general or considered collectively',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_64',
      word: 'picture',
      definition:
        'A painting, drawing, photograph, or other representation on a surface',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_65',
      word: 'plane',
      definition:
        'A vehicle that flies through the air and has wings and at least one engine',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_66',
      word: 'plant',
      definition:
        'A living organism that typically grows in a permanent site, absorbs water and nutrients through its roots',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_67',
      word: 'plate',
      definition:
        'A flat dish, typically circular, from which food is eaten or served',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_68',
      word: 'play',
      definition:
        'To engage in activity for enjoyment and recreation rather than a serious or practical purpose',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_69',
      word: 'please',
      definition:
        'A polite word used when asking for something or when showing someone appreciation',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_70',
      word: 'police',
      definition:
        'The civil force of a state, responsible for the prevention and detection of crime and the maintenance of public order',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_71',
      word: 'potato',
      definition: 'A starchy plant tuber which is a popular food',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_72',
      word: 'problem',
      definition:
        'A matter or situation regarded as unwelcome or harmful and needing to be dealt with and overcome',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_73',
      word: 'purple',
      definition: 'A color intermediate between red and blue',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_74',
      word: 'question',
      definition: 'A sentence worded or expressed so as to elicit information',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_75',
      word: 'quick',
      definition: 'Moving fast or doing something in a short time',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_76',
      word: 'quiet',
      definition: 'Making little or no noise',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_77',
      word: 'radio',
      definition:
        'The transmission and reception of electromagnetic waves of radio frequency, especially for broadcasting programs',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_78',
      word: 'rain',
      definition:
        'Moisture condensed from the atmosphere that falls visibly in separate drops',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_79',
      word: 'read',
      definition:
        'To look at and comprehend the meaning of written or printed matter by mentally interpreting the characters or symbols of which it is composed',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_80',
      word: 'red',
      definition: 'The color of blood or fire',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_81',
      word: 'remember',
      definition:
        'To have or keep an image or idea in your mind of something from the past',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_82',
      word: 'restaurant',
      definition:
        'A place where people pay to sit and eat meals that are prepared and served on the premises',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_83',
      word: 'rice',
      definition:
        'A cereal grain that is the seed of a grass species, consumed as a staple food',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_84',
      word: 'river',
      definition:
        'A large natural stream of water flowing in a channel to the sea, a lake, or another such stream',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_85',
      word: 'road',
      definition:
        'A wide way leading from one place to another, especially one with a specially prepared surface',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_86',
      word: 'room',
      definition:
        'A part or division of a building enclosed by walls, floor, and ceiling',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_87',
      word: 'run',
      definition:
        'To move at a speed faster than a walk, never having both feet on the ground at the same time',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_88',
      word: 'sad',
      definition: 'Feeling or showing sorrow; unhappy',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_89',
      word: 'salt',
      definition:
        'A white crystalline substance that gives seawater its characteristic taste and is used for seasoning or preserving food',
      difficulty: 'A1',
      level: 'A1',
    },
    {
      id: 'a1_90',
      word: 'sand',
      definition:
        'A loose granular substance, typically pale yellowish brown, resulting from the erosion of siliceous and other rocks',
      difficulty: 'A1',
      level: 'A1',
    },
  ],
  A2: [
    {
      id: 'a2_1',
      word: 'ability',
      definition: 'The fact that someone or something is able to do something',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_2',
      word: 'adventure',
      definition: 'An unusual and exciting experience or activity',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_3',
      word: 'celebrate',
      definition:
        'To acknowledge a significant day or event with a social gathering or enjoyable activity',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_4',
      word: 'distance',
      definition: 'The amount of space between two things or points',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_5',
      word: 'furniture',
      definition:
        'Large movable equipment such as tables, chairs, or beds, used in a home or office',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_6',
      word: 'accident',
      definition:
        'An unfortunate event that happens unexpectedly and unintentionally',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_7',
      word: 'holiday',
      definition:
        'A period in which a person does not work and is free to relax',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_8',
      word: 'weather',
      definition:
        'The state of the atmosphere at a place and time regarding heat, cloudiness, dryness, sunshine, wind, rain, etc.',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_9',
      word: 'cooking',
      definition: 'The practice or skill of preparing food',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_10',
      word: 'education',
      definition: 'The process of receiving or giving systematic instruction',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_11',
      word: 'hobby',
      definition:
        'An activity done regularly for enjoyment during leisure time',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_12',
      word: 'dangerous',
      definition: 'Able or likely to cause harm or injury',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_13',
      word: 'exciting',
      definition: 'Causing great enthusiasm and eagerness',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_14',
      word: 'important',
      definition: 'Of great significance or value',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_15',
      word: 'boring',
      definition: 'Not interesting; tedious',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_16',
      word: 'journey',
      definition: 'An act of traveling from one place to another',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_17',
      word: 'luggage',
      definition: 'Bags and belongings that you carry with you when traveling',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_18',
      word: 'weekend',
      definition: 'Saturday and Sunday',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_19',
      word: 'bathroom',
      definition:
        'A room containing a bathtub or shower and usually a washbasin and toilet',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_20',
      word: 'bedroom',
      definition: 'A room for sleeping in',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_21',
      word: 'abroad',
      definition: 'In or to a foreign country',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_22',
      word: 'actually',
      definition: 'Used to emphasize that something is true or exact',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_23',
      word: 'competition',
      definition: 'An event in which people compete to win',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_24',
      word: 'creative',
      definition: 'Having good imagination or original ideas',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_25',
      word: 'cycling',
      definition: 'The sport or activity of riding a bicycle',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_26',
      word: 'library',
      definition: 'A building containing books for people to read or borrow',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_27',
      word: 'message',
      definition: 'A verbal, written, or recorded communication',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_28',
      word: 'mistake',
      definition: 'An error or something done incorrectly',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_29',
      word: 'quality',
      definition: 'The standard of something compared to other similar things',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_30',
      word: 'website',
      definition: 'A location on the World Wide Web with related pages',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_31',
      word: 'calendar',
      definition:
        'A chart or series of pages showing the days, weeks, and months of a particular year',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_32',
      word: 'camping',
      definition:
        'The activity of spending a vacation living in a camp, tent, or camper',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_33',
      word: 'castle',
      definition:
        'A large building, typically of the medieval period, fortified against attack',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_34',
      word: 'comedy',
      definition:
        'Professional entertainment consisting of jokes and sketches intended to make an audience laugh',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_35',
      word: 'discussion',
      definition:
        'The action or process of talking about something in order to reach a decision',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_36',
      word: 'fitness',
      definition: 'The condition of being physically fit and healthy',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_37',
      word: 'horror',
      definition:
        'An intense feeling of fear, shock, or disgust; a genre of movie or book',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_38',
      word: 'magazine',
      definition:
        'A periodical publication containing articles and illustrations',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_39',
      word: 'temperature',
      definition:
        'The degree or intensity of heat present in a substance or object',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_40',
      word: 'vacation',
      definition:
        'A period spent away from home or business in travel or recreation',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_41',
      word: 'airport',
      definition:
        'A complex of buildings and runways for aircraft to take off and land',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_42',
      word: 'appointment',
      definition:
        'An arrangement to meet someone at a particular time and place',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_43',
      word: 'concert',
      definition:
        'A musical performance given in public by one or more performers',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_44',
      word: 'dessert',
      definition: 'The sweet course eaten at the end of a meal',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_45',
      word: 'favorite',
      definition: 'Preferred to all others of the same kind',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_46',
      word: 'helpful',
      definition: 'Giving or ready to give help',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_47',
      word: 'invitation',
      definition:
        'A written or verbal request inviting someone to go somewhere or do something',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_48',
      word: 'nationality',
      definition: 'The status of belonging to a particular nation',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_49',
      word: 'delicious',
      definition: 'Highly pleasant to the taste',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_50',
      word: 'successful',
      definition: 'Accomplishing a desired aim or result',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_51',
      word: 'activity',
      definition: 'Something that a person or group does',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_52',
      word: 'adult',
      definition:
        'A fully grown person who is legally responsible for their actions',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_53',
      word: 'ancient',
      definition:
        'Belonging to the very distant past and no longer in existence',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_54',
      word: 'arrive',
      definition: 'To reach a place at the end of a journey',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_55',
      word: 'athlete',
      definition: 'A person who competes in one or more sports',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_56',
      word: 'beginning',
      definition: 'The point in time or space at which something starts',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_57',
      word: 'cheerful',
      definition: 'Noticeably happy and optimistic',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_58',
      word: 'cinema',
      definition: 'A theater where films are shown for public entertainment',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_59',
      word: 'clothing',
      definition: 'Items worn to cover the body',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_60',
      word: 'cloudy',
      definition: 'Full of or covered with clouds',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_61',
      word: 'connect',
      definition: 'To join or link two or more things together',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_62',
      word: 'conversation',
      definition:
        'A talk between two or more people in which thoughts and feelings are expressed',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_63',
      word: 'describe',
      definition: 'To give an account in words of someone or something',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_64',
      word: 'dictionary',
      definition:
        'A book or electronic resource that lists words and explains their meanings',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_65',
      word: 'difference',
      definition: 'A point or way in which people or things are dissimilar',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_66',
      word: 'different',
      definition: 'Not the same as another or each other',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_67',
      word: 'difficult',
      definition: 'Needing much effort or skill to accomplish or understand',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_68',
      word: 'direction',
      definition: 'The course along which something moves or points',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_69',
      word: 'discover',
      definition:
        'To find something or someone unexpectedly or in the course of a search',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_70',
      word: 'drawings',
      definition: 'Pictures or diagrams made with a pencil, pen, or crayon',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_71',
      word: 'electronic',
      definition:
        'Having or operating with components such as microchips and transistors',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_72',
      word: 'expensive',
      definition: 'Costing a lot of money',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_73',
      word: 'experience',
      definition: 'Practical contact with and observation of facts or events',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_74',
      word: 'festival',
      definition:
        'A day or period of celebration, typically for religious reasons',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_75',
      word: 'foreign',
      definition:
        "Of, from, in, or characteristic of a country or language other than one's own",
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_76',
      word: 'geography',
      definition:
        'The study of the physical features of the earth and human impact on them',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_77',
      word: 'goodbye',
      definition: 'An expression used when leaving or ending a conversation',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_78',
      word: 'history',
      definition: 'The study of past events, particularly in human affairs',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_79',
      word: 'hospital',
      definition:
        'An institution providing medical treatment and nursing care for sick or injured people',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_80',
      word: 'interesting',
      definition: "Arousing curiosity or engaging one's attention",
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_56',
      word: 'meeting',
      definition:
        'An assembly of people for a particular purpose, especially for formal discussion',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_57',
      word: 'memory',
      definition:
        'The faculty by which the mind stores and remembers information',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_58',
      word: 'message',
      definition:
        'A verbal, written, or recorded communication sent to or left for a recipient who cannot be contacted directly',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_59',
      word: 'midnight',
      definition: "Twelve o'clock at night",
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_60',
      word: 'minute',
      definition:
        'A period of time equal to sixty seconds or a sixtieth of an hour',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_61',
      word: 'mistake',
      definition:
        'An error or fault resulting from defective judgment, deficient knowledge, or carelessness',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_62',
      word: 'modern',
      definition:
        'Relating to the present or recent times as opposed to the remote past',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_63',
      word: 'moment',
      definition: 'A very brief period of time',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_64',
      word: 'month',
      definition:
        'Each of the twelve named periods into which a year is divided',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_65',
      word: 'mountain',
      definition:
        "A large natural elevation of the earth's surface rising abruptly from the surrounding level",
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_66',
      word: 'movie',
      definition:
        'A story or event recorded by a camera as a set of moving images and shown in a theater or on television',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_67',
      word: 'museum',
      definition:
        'A building in which objects of historical, scientific, artistic, or cultural interest are stored and exhibited',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_68',
      word: 'music',
      definition:
        'Vocal or instrumental sounds combined in such a way as to produce beauty of form, harmony, and expression of emotion',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_69',
      word: 'necessary',
      definition:
        'Required to be done, achieved, or present; needed; essential',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_70',
      word: 'neighbor',
      definition:
        'A person living near or next door to the speaker or person referred to',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_71',
      word: 'nervous',
      definition:
        'Easily agitated or alarmed; tending to be anxious; highly strung',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_72',
      word: 'newspaper',
      definition:
        'A printed publication consisting of folded, unstapled sheets and containing news, articles, advertisements, and other features',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_73',
      word: 'normal',
      definition: 'Conforming to a standard; usual, typical, or expected',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_74',
      word: 'north',
      definition:
        'The direction in which a compass needle normally points, toward the horizon on the left side of a person facing east',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_75',
      word: 'notebook',
      definition: 'A book with blank or ruled pages for writing notes in',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_76',
      word: 'notice',
      definition: 'To become aware of; to observe or pay attention to',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_77',
      word: 'number',
      definition:
        'An arithmetical value, expressed by a word, symbol, or figure, representing a particular quantity',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_78',
      word: 'ocean',
      definition:
        'A very large expanse of sea, in particular each of the main areas into which the sea is divided geographically',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_79',
      word: 'office',
      definition:
        'A room, set of rooms, or building used as a place for commercial, professional, or bureaucratic work',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_80',
      word: 'official',
      definition:
        'Relating to an authority or public body and its duties, actions, and responsibilities',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_81',
      word: 'opposite',
      definition: 'Having a position on the other or further side of something',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_82',
      word: 'ordinary',
      definition: 'With no special or distinctive features; normal or usual',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_83',
      word: 'organize',
      definition: 'To arrange or structure in a systematic way',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_84',
      word: 'original',
      definition: 'Present or existing from the beginning; first or earliest',
      difficulty: 'A2',
      level: 'A2',
    },
    {
      id: 'a2_85',
      word: 'outside',
      definition: 'The external side or surface of something',
      difficulty: 'A2',
      level: 'A2',
    },
  ],
  B1: [
    {
      id: 'b1_1',
      word: 'ambitious',
      definition:
        'Having or showing a strong desire and determination to succeed',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_2',
      word: 'anonymous',
      definition: 'Having no known name or identity',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_3',
      word: 'anticipate',
      definition: 'To regard as probable; expect or predict',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_4',
      word: 'anxious',
      definition:
        'Feeling or showing worry, nervousness, or unease about something with an uncertain outcome',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_5',
      word: 'apparently',
      definition: 'As far as one knows or can see; seemingly',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_6',
      word: 'appreciate',
      definition: 'To recognize the full worth of something',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_7',
      word: 'appropriate',
      definition: 'Suitable or proper in the circumstances',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_8',
      word: 'authorize',
      definition: 'To give official permission for or approval to',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_9',
      word: 'availability',
      definition: 'The quality of being able to be used or obtained',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_10',
      word: 'beneficial',
      definition: 'Resulting in good; favorable or advantageous',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_11',
      word: 'capability',
      definition: 'The power or ability to do something',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_12',
      word: 'charitable',
      definition: 'Generous in giving money, help, or time to those in need',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_13',
      word: 'circumstance',
      definition:
        'A fact or condition connected with or relevant to an event or action',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_14',
      word: 'collaborate',
      definition: 'To work jointly on an activity or project',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_15',
      word: 'compelling',
      definition:
        'Evoking interest, attention, or admiration in a powerfully irresistible way',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_16',
      word: 'comprehend',
      definition: 'To grasp mentally; understand',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_17',
      word: 'concede',
      definition:
        'To admit or agree that something is true after first denying or resisting it',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_18',
      word: 'conceive',
      definition: 'To form or devise an idea, plan, etc. in the mind',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_19',
      word: 'condemn',
      definition: 'To express complete disapproval of; censure',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_20',
      word: 'conducive',
      definition: 'Making a certain situation or outcome likely or possible',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_21',
      word: 'confidential',
      definition: 'Intended to be kept secret or private',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_22',
      word: 'confine',
      definition:
        'To keep or restrict someone or something within certain limits of space, scope, or time',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_23',
      word: 'confront',
      definition:
        'To face up to and deal with a problem or difficult situation',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_24',
      word: 'considerate',
      definition: 'Careful not to cause inconvenience or hurt to others',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_25',
      word: 'consistent',
      definition:
        'Acting or done in the same way over time, especially so as to be fair or accurate',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_26',
      word: 'conspicuous',
      definition:
        'Standing out so as to be clearly visible; attracting notice or attention',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_27',
      word: 'contribute',
      definition:
        'To give something, especially money, in order to help achieve or provide something',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_28',
      word: 'convenient',
      definition:
        "Fitting in well with a person's needs, activities, and plans",
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_29',
      word: 'conventional',
      definition:
        'Based on or in accordance with what is generally done or believed',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_30',
      word: 'convert',
      definition: 'To change in form, character, or function',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_31',
      word: 'coordinate',
      definition:
        'To bring the different elements of a complex activity or organization into a harmonious or efficient relationship',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_32',
      word: 'creativity',
      definition:
        'The use of imagination or original ideas to create something',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_33',
      word: 'criticism',
      definition:
        'The expression of disapproval of someone or something based on perceived faults or mistakes',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_34',
      word: 'crucial',
      definition:
        'Decisive or critical, especially in the success or failure of something',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_35',
      word: 'currency',
      definition: 'A system of money in general use in a particular country',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_36',
      word: 'curriculum',
      definition:
        'The subjects comprising a course of study in a school or college',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_37',
      word: 'deadline',
      definition:
        'The latest time or date by which something should be completed',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_38',
      word: 'declaration',
      definition: 'A formal or explicit statement or announcement',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_39',
      word: 'decorate',
      definition:
        'To make something look more attractive by adding extra items or images to it',
      difficulty: 'B1',
      level: 'B1',
    },
    {
      id: 'b1_40',
      word: 'decrease',
      definition:
        'To make or become smaller in size, amount, intensity, or degree',
      difficulty: 'B1',
      level: 'B1',
    },
  ],
  C1: [
    {
      id: 'c1_1',
      word: 'comprehensive',
      definition:
        'Including or dealing with all or nearly all elements or aspects of something',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_2',
      word: 'deteriorate',
      definition: 'To become progressively worse',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_3',
      word: 'indispensable',
      definition: 'Absolutely necessary; essential',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_4',
      word: 'sophisticated',
      definition:
        'Having a great deal of worldly experience and knowledge of culture',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_5',
      word: 'unprecedented',
      definition: 'Never done or known before',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_6',
      word: 'advocate',
      definition: 'To publicly recommend or support',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_7',
      word: 'ambiguity',
      definition: 'The quality of being open to more than one interpretation',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_8',
      word: 'circumvent',
      definition: 'To find a way around an obstacle',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_9',
      word: 'correlation',
      definition:
        'A mutual relationship or connection between two or more things',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_10',
      word: 'diminish',
      definition: 'To make or become less',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_11',
      word: 'adjacent',
      definition: 'Next to or adjoining something else',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_12',
      word: 'articulate',
      definition:
        'Having or showing the ability to speak fluently and coherently',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_13',
      word: 'consensus',
      definition: 'General agreement about something',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_14',
      word: 'contentious',
      definition: 'Causing or likely to cause an argument; controversial',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_15',
      word: 'converge',
      definition:
        'To come together from different directions so as to eventually meet',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_16',
      word: 'credibility',
      definition: 'The quality of being trusted and believed in',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_17',
      word: 'culminate',
      definition: 'To reach a climax or point of highest development',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_18',
      word: 'feasible',
      definition: 'Possible to do easily or conveniently',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_19',
      word: 'integrity',
      definition:
        'The quality of being honest and having strong moral principles',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_20',
      word: 'predominant',
      definition: 'Present as the strongest or main element',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_21',
      word: 'acquisition',
      definition: 'The act of acquiring or gaining possession of something',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_22',
      word: 'complexity',
      definition: 'The state of being complicated or intricate',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_23',
      word: 'diplomatic',
      definition: 'Tactful and sensitive in dealing with others',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_24',
      word: 'empirical',
      definition: 'Based on observation or experience rather than theory',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_25',
      word: 'facilitate',
      definition: 'To make an action or process easier',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_26',
      word: 'hierarchy',
      definition:
        'A system in which people or things are arranged according to their importance',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_27',
      word: 'integration',
      definition: 'The action of combining things to form a whole',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_28',
      word: 'jurisdiction',
      definition: 'The official power to make legal decisions and judgments',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_29',
      word: 'manipulation',
      definition: 'The action of manipulating something in a skillful manner',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_30',
      word: 'theoretical',
      definition:
        'Concerned with or involving the theory of a subject or area of study',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_31',
      word: 'abolish',
      definition:
        'To formally put an end to a system, practice, or institution',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_32',
      word: 'accountability',
      definition:
        'The fact of being responsible for what you do and able to explain it',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_33',
      word: 'confer',
      definition: 'To have discussions; to grant or bestow',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_34',
      word: 'deviate',
      definition: 'To depart from an established course or standard',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_35',
      word: 'endeavour',
      definition: 'An attempt to achieve a goal',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_36',
      word: 'explicit',
      definition: 'Stated clearly and in detail, leaving no room for confusion',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_37',
      word: 'formulate',
      definition: 'To develop or express in a precise, systematic way',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_38',
      word: 'hypothetical',
      definition: 'Based on or serving as a hypothesis; supposed',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_39',
      word: 'meticulous',
      definition: 'Showing great attention to detail; very careful and precise',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_40',
      word: 'substantiate',
      definition:
        'To provide evidence to support or prove the truth of something',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_41',
      word: 'assimilate',
      definition: 'To absorb and integrate into a society or culture',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_42',
      word: 'coherent',
      definition: 'Logical and consistent; having clarity or intelligibility',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_43',
      word: 'dilemma',
      definition:
        'A situation requiring a choice between equally undesirable alternatives',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_44',
      word: 'elaborate',
      definition:
        'Involving many carefully arranged parts or details; developed or presented in detail',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_45',
      word: 'fluctuate',
      definition: 'To rise and fall irregularly in number or amount',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_46',
      word: 'implications',
      definition:
        'The conclusion that can be drawn from something although it is not explicitly stated',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_47',
      word: 'intermediary',
      definition:
        'A person who acts as a link between people in order to bring about an agreement',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_48',
      word: 'lucrative',
      definition: 'Producing a great deal of profit',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_49',
      word: 'methodology',
      definition:
        'A system of methods used in a particular area of study or activity',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_50',
      word: 'mitigate',
      definition: 'To make less severe, serious, or painful',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_51',
      word: 'obsolete',
      definition: 'No longer produced or used; out of date',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_52',
      word: 'plausible',
      definition: 'Seeming reasonable or probable; believable',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_53',
      word: 'prevalent',
      definition: 'Widespread in a particular area or at a particular time',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_54',
      word: 'scrutinize',
      definition: 'To examine or inspect closely and thoroughly',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_55',
      word: 'sovereignty',
      definition:
        'Supreme power or authority; the authority of a state to govern itself',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_56',
      word: 'accumulate',
      definition:
        'To gather or acquire an increasing number or quantity of something over time',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_57',
      word: 'adaptation',
      definition: 'The action or process of adapting or being adapted',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_58',
      word: 'adhere',
      definition:
        'To stick fast to a surface or substance; to follow, observe, or uphold',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_59',
      word: 'advocate',
      definition: 'To publicly recommend or support a particular cause',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_60',
      word: 'aggravate',
      definition: 'To make a problem, injury, or offense worse or more serious',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_61',
      word: 'alleviate',
      definition: 'To make suffering, deficiency, or a problem less severe',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_62',
      word: 'analogy',
      definition:
        'A comparison between one thing and another, typically for the purpose of explanation or clarification',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_63',
      word: 'anomaly',
      definition:
        'Something that deviates from what is standard, normal, or expected',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_64',
      word: 'anticipation',
      definition:
        'The action of anticipating something; expectation or prediction',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_65',
      word: 'apathy',
      definition: 'Lack of interest, enthusiasm, or concern',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_66',
      word: 'apparatus',
      definition:
        'The technical equipment or machinery needed for a particular activity or purpose',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_67',
      word: 'apprehension',
      definition:
        'Anxiety or fear that something bad or unpleasant will happen',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_68',
      word: 'aptitude',
      definition: 'A natural ability to do something or learn something well',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_69',
      word: 'arduous',
      definition:
        'Involving or requiring strenuous effort; difficult and tiring',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_70',
      word: 'articulation',
      definition:
        'The action of expressing thoughts or feelings clearly in words',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_71',
      word: 'ascertain',
      definition: 'To find out definitely; to make certain',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_72',
      word: 'aspiration',
      definition: 'A hope or ambition of achieving something',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_73',
      word: 'assertion',
      definition: 'A confident and forceful statement of fact or belief',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_74',
      word: 'assessment',
      definition:
        'The evaluation or estimation of the nature, quality, or ability of someone or something',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_75',
      word: 'assimilation',
      definition:
        'The process of taking in and fully understanding information or ideas',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_76',
      word: 'assumption',
      definition:
        'A thing that is accepted as true or as certain to happen, without proof',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_77',
      word: 'attainment',
      definition: 'The action or process of achieving a goal',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_78',
      word: 'augment',
      definition: 'To make something greater by adding to it; to increase',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_79',
      word: 'authenticity',
      definition: 'The quality of being authentic or genuine',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_80',
      word: 'autonomy',
      definition:
        'The right or condition of self-government; freedom from external control or influence',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_81',
      word: 'belligerent',
      definition:
        'Hostile and aggressive; demonstrating a willingness to fight',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_82',
      word: 'catalyst',
      definition: 'A person or thing that precipitates an event or change',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_83',
      word: 'clandestine',
      definition: 'Kept secret or done secretively, especially because illicit',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_84',
      word: 'cognitive',
      definition:
        'Relating to cognition, or the mental processes involved in acquiring knowledge and understanding',
      difficulty: 'C1',
      level: 'C1',
    },
    {
      id: 'c1_85',
      word: 'compelling',
      definition:
        'Evoking interest, attention, or admiration in a powerfully irresistible way',
      difficulty: 'C1',
      level: 'C1',
    },
  ],
  C2: [
    {
      id: 'c2_1',
      word: 'arbitrary',
      definition:
        'Based on random choice or personal whim, rather than any reason or system',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_2',
      word: 'equivocal',
      definition: 'Open to more than one interpretation; ambiguous',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_3',
      word: 'insidious',
      definition:
        'Proceeding in a gradual, subtle way, but with harmful effects',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_4',
      word: 'meticulous',
      definition: 'Showing great attention to detail; very careful and precise',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_5',
      word: 'ubiquitous',
      definition: 'Present, appearing, or found everywhere',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_6',
      word: 'aberration',
      definition: 'A departure from what is normal, usual, or expected',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_7',
      word: 'cacophony',
      definition: 'A harsh, discordant mixture of sounds',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_8',
      word: 'ethereal',
      definition:
        'Extremely delicate and light in a way that seems not to be of this world',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_9',
      word: 'juxtaposition',
      definition:
        'The act of placing two things next to each other for comparison or contrast',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_10',
      word: 'paradigm',
      definition: 'A typical example or pattern of something; a model',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_11',
      word: 'acquiesce',
      definition: 'To accept something reluctantly but without protest',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_12',
      word: 'anachronistic',
      definition: 'Belonging to a period other than that being portrayed',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_13',
      word: 'capricious',
      definition:
        'Given to sudden and unaccountable changes of mood or behavior',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_14',
      word: 'disingenuous',
      definition:
        'Not candid or sincere, typically by pretending that one knows less about something than one actually does',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_15',
      word: 'egregious',
      definition: 'Outstandingly bad; shocking',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_16',
      word: 'ephemeral',
      definition: 'Lasting for a very short time',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_17',
      word: 'esoteric',
      definition:
        'Intended for or likely to be understood by only a small number of people with specialized knowledge',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_18',
      word: 'fastidious',
      definition: 'Very attentive to and concerned about accuracy and detail',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_19',
      word: 'nuance',
      definition:
        'A subtle difference in or shade of meaning, expression, or sound',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_20',
      word: 'surreptitious',
      definition: 'Kept secret, especially because it would not be approved of',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_21',
      word: 'abstruse',
      definition: 'Difficult to understand; obscure',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_22',
      word: 'circumlocution',
      definition: 'The use of many words where fewer would do',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_23',
      word: 'deleterious',
      definition: 'Causing harm or damage',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_24',
      word: 'efficacious',
      definition: 'Successfully producing the intended result; effective',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_25',
      word: 'fastidious',
      definition: 'Very attentive to and concerned about accuracy and detail',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_26',
      word: 'garrulous',
      definition: 'Excessively talkative, especially on trivial matters',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_27',
      word: 'harangue',
      definition: 'A lengthy and aggressive speech',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_28',
      word: 'incontrovertible',
      definition: 'Not able to be denied or disputed',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_29',
      word: 'laconic',
      definition: 'Using very few words; concise',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_30',
      word: 'mellifluous',
      definition: 'Sweet or musical; pleasant to hear',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_31',
      word: 'nebulous',
      definition: 'In the form of a cloud or haze; vague or ill-defined',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_32',
      word: 'obfuscate',
      definition: 'To make obscure, unclear, or unintelligible',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_33',
      word: 'perspicacious',
      definition: 'Having a ready insight into and understanding of things',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_34',
      word: 'quintessential',
      definition:
        'Representing the most perfect or typical example of a quality or class',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_35',
      word: 'recalcitrant',
      definition:
        'Having an obstinately uncooperative attitude toward authority',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_36',
      word: 'sagacious',
      definition: 'Having or showing keen mental discernment and good judgment',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_37',
      word: 'tenacious',
      definition:
        'Tending to keep a firm hold of something; clinging or adhering closely',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_38',
      word: 'ubiquity',
      definition: 'The fact of appearing everywhere or of being very common',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_39',
      word: 'vicissitude',
      definition:
        'A change of circumstances or fortune, typically one that is unwelcome',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_40',
      word: 'zealous',
      definition:
        'Having or showing great energy or enthusiasm in pursuit of a cause or objective',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_41',
      word: 'ambivalent',
      definition:
        'Having mixed feelings or contradictory ideas about something or someone',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_42',
      word: 'conundrum',
      definition: 'A confusing and difficult problem or question',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_43',
      word: 'didactic',
      definition:
        'Intended to teach, particularly in having moral instruction as an ulterior motive',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_44',
      word: 'elucidate',
      definition: 'To make something clear; to explain or clarify',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_45',
      word: 'filibuster',
      definition:
        'An action such as prolonged speaking that obstructs progress in a legislative assembly',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_46',
      word: 'grandiloquent',
      definition: 'Using high-flown or bombastic language; pompous in style',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_47',
      word: 'hegemony',
      definition:
        'Leadership or dominance, especially by one country or social group over others',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_48',
      word: 'inexorable',
      definition: 'Impossible to stop or prevent; continuing relentlessly',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_49',
      word: 'judiciously',
      definition: 'Showing good judgment or sense; prudently',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_50',
      word: 'kaleidoscopic',
      definition:
        'Having complex patterns of colors or elements; continually changing',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_51',
      word: 'loquacious',
      definition: 'Tending to talk a great deal; garrulous',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_52',
      word: 'machiavellian',
      definition: 'Cunning, scheming, and unscrupulous, especially in politics',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_53',
      word: 'nefarious',
      definition: 'Extremely wicked or villainous; criminal',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_54',
      word: 'obstreperous',
      definition: 'Noisy and difficult to control; stubbornly defiant',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_55',
      word: 'pontificate',
      definition: "To express one's opinions in a pompous and dogmatic way",
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_56',
      word: 'quagmire',
      definition:
        'A difficult or precarious situation; a soft boggy area of land',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_57',
      word: 'recondite',
      definition: 'Little known or difficult to understand; abstruse',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_58',
      word: 'soliloquy',
      definition:
        "An act of speaking one's thoughts aloud when alone or regardless of any hearers",
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_59',
      word: 'tautology',
      definition:
        'The saying of the same thing twice in different words; needless repetition',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_60',
      word: 'unequivocal',
      definition: 'Leaving no doubt; unambiguous; clear and explicit',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_61',
      word: 'vicarious',
      definition:
        'Experienced in the imagination through the feelings or actions of another person',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_62',
      word: 'wistful',
      definition: 'Having or showing a feeling of vague or regretful longing',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_63',
      word: 'xenophobia',
      definition: 'Dislike of or prejudice against people from other countries',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_64',
      word: 'yearning',
      definition: 'A feeling of intense longing for something',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_65',
      word: 'zeitgeist',
      definition:
        'The defining spirit or mood of a particular period of history as shown by the ideas and beliefs of the time',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_66',
      word: 'antediluvian',
      definition:
        'Extremely old-fashioned or outdated; belonging to the time before the biblical flood',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_67',
      word: 'byzantine',
      definition:
        'Excessively complicated, typically involving a great deal of administrative detail',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_68',
      word: 'chimerical',
      definition:
        'Existing only as the product of unchecked imagination; fantastically visionary',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_69',
      word: 'demagogue',
      definition:
        'A political leader who seeks support by appealing to popular desires and prejudices',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_70',
      word: 'equanimity',
      definition: 'Calmness and composure, especially in a difficult situation',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_71',
      word: 'facetious',
      definition:
        'Treating serious issues with deliberately inappropriate humor',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_72',
      word: 'gainsay',
      definition: 'To deny or contradict a fact or statement',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_73',
      word: 'hermetic',
      definition:
        'Completely sealed, especially against air; impervious to outside influences',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_74',
      word: 'idiosyncrasy',
      definition:
        'A distinctive or peculiar feature or characteristic of a place or person',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_75',
      word: 'juggernaut',
      definition: 'A huge, powerful, and overwhelming force or institution',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_76',
      word: 'labyrinthine',
      definition:
        'Resembling a labyrinth in being complicated and difficult to follow',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_77',
      word: 'moribund',
      definition: 'In terminal decline; lacking vitality or vigor',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_78',
      word: 'nomenclature',
      definition:
        'The devising or choosing of names for things, especially in a science or other discipline',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_79',
      word: 'obsequious',
      definition: 'Obedient or attentive to an excessive or servile degree',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_80',
      word: 'pernicious',
      definition:
        'Having a harmful effect, especially in a gradual or subtle way',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_56',
      word: 'capitulate',
      definition: 'To surrender or give up under specified conditions',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_57',
      word: 'catharsis',
      definition:
        'The process of releasing strong or repressed emotions through art or drama',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_58',
      word: 'circumlocution',
      definition:
        'The use of many words where fewer would do, especially in a deliberate attempt to be vague or evasive',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_59',
      word: 'circumnavigate',
      definition:
        'To sail or travel all the way around something, especially the world',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_60',
      word: 'circumscribe',
      definition:
        'To restrict or limit something within bounds or specific parameters',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_61',
      word: 'circumspect',
      definition:
        'Wary and unwilling to take risks; carefully considering all circumstances and consequences',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_62',
      word: 'circumvent',
      definition:
        'To find a way around an obstacle, especially ingeniously or illegally',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_63',
      word: 'clandestine',
      definition: 'Kept secret or done secretively, especially because illicit',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_64',
      word: 'clemency',
      definition:
        'Mercy or leniency shown toward offenders by a person or agency with authority to punish',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_65',
      word: 'cogent',
      definition:
        'Clear, logical, and convincing; compelling belief or agreement',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_66',
      word: 'cognizant',
      definition: 'Having knowledge or awareness of something',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_67',
      word: 'commensurate',
      definition: 'Corresponding in size or degree; in proportion',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_68',
      word: 'compendium',
      definition:
        'A collection of concise but detailed information about a particular subject',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_69',
      word: 'complacency',
      definition:
        "A feeling of smug or uncritical satisfaction with oneself or one's achievements",
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_70',
      word: 'complicity',
      definition:
        'The state of being involved with others in an illegal activity or wrongdoing',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_71',
      word: 'conciliatory',
      definition: 'Intended or likely to placate or pacify',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_72',
      word: 'concomitant',
      definition: 'Naturally accompanying or associated with something',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_73',
      word: 'condescension',
      definition: 'An attitude of patronizing superiority; disdain',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_74',
      word: 'conflagration',
      definition:
        'An extensive fire that destroys a great deal of land or property',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_75',
      word: 'confluence',
      definition:
        'The junction of two rivers, especially rivers of approximately equal width',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_76',
      word: 'conflate',
      definition: 'To combine or blend two or more elements or texts into one',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_77',
      word: 'connoisseur',
      definition:
        'An expert judge in matters of taste, especially in the fine arts, food, or wine',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_78',
      word: 'conscientious',
      definition: 'Diligent, careful, and thorough; governed by conscience',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_79',
      word: 'conspicuous',
      definition:
        'Standing out so as to be clearly visible; attracting attention',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_80',
      word: 'contrite',
      definition:
        'Feeling or expressing remorse or penitence; affected by guilt',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_81',
      word: 'convolution',
      definition:
        'A twist, fold, or coil, especially a complex one; an intricacy or complexity',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_82',
      word: 'corpulent',
      definition: 'Having a large, heavy, bulky body; obese',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_83',
      word: 'credulous',
      definition: 'Having or showing too great a readiness to believe things',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_84',
      word: 'cryptic',
      definition: 'Having a meaning that is mysterious or obscure; enigmatic',
      difficulty: 'C2',
      level: 'C2',
    },
    {
      id: 'c2_85',
      word: 'culmination',
      definition:
        'The highest or climactic point of something, especially as attained after a long time',
      difficulty: 'C2',
      level: 'C2',
    },
  ],
  B2: [
    {
      id: 'b2_1',
      word: 'accessible',
      definition: 'Able to be reached, entered, used, or understood',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_2',
      word: 'accountability',
      definition: 'The fact or condition of being accountable; responsibility',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_3',
      word: 'advocate',
      definition:
        'To publicly recommend or support a particular policy or cause',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_4',
      word: 'alternatively',
      definition:
        'In a way that offers or expresses a choice between two or more things',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_5',
      word: 'ambitious',
      definition:
        'Having or showing a strong desire and determination to succeed',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_6',
      word: 'anonymous',
      definition: 'Having no known name or identity',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_7',
      word: 'anticipate',
      definition: 'To regard as probable; expect or predict',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_8',
      word: 'anxious',
      definition:
        'Feeling or showing worry, nervousness, or unease about something with an uncertain outcome',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_9',
      word: 'apparently',
      definition: 'As far as one knows or can see; seemingly',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_10',
      word: 'appreciate',
      definition: 'To recognize the full worth of something',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_11',
      word: 'appropriate',
      definition: 'Suitable or proper in the circumstances',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_12',
      word: 'authorize',
      definition: 'To give official permission for or approval to',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_13',
      word: 'availability',
      definition: 'The quality of being able to be used or obtained',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_14',
      word: 'beneficial',
      definition: 'Resulting in good; favorable or advantageous',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_15',
      word: 'capability',
      definition: 'The power or ability to do something',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_16',
      word: 'charitable',
      definition: 'Generous in giving money, help, or time to those in need',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_17',
      word: 'circumstance',
      definition:
        'A fact or condition connected with or relevant to an event or action',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_18',
      word: 'collaborate',
      definition: 'To work jointly on an activity or project',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_19',
      word: 'compelling',
      definition:
        'Evoking interest, attention, or admiration in a powerfully irresistible way',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_20',
      word: 'comprehend',
      definition: 'To grasp mentally; understand',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_21',
      word: 'concede',
      definition:
        'To admit or agree that something is true after first denying or resisting it',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_22',
      word: 'conceive',
      definition: 'To form or devise an idea, plan, etc. in the mind',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_23',
      word: 'condemn',
      definition: 'To express complete disapproval of; censure',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_24',
      word: 'conducive',
      definition: 'Making a certain situation or outcome likely or possible',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_25',
      word: 'confidential',
      definition: 'Intended to be kept secret or private',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_26',
      word: 'confine',
      definition:
        'To keep or restrict someone or something within certain limits of space, scope, or time',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_27',
      word: 'confront',
      definition:
        'To face up to and deal with a problem or difficult situation',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_28',
      word: 'considerate',
      definition: 'Careful not to cause inconvenience or hurt to others',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_29',
      word: 'consistent',
      definition:
        'Acting or done in the same way over time, especially so as to be fair or accurate',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_30',
      word: 'conspicuous',
      definition:
        'Standing out so as to be clearly visible; attracting notice or attention',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_31',
      word: 'contemplate',
      definition: 'To look thoughtfully for a long time at; to think about',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_32',
      word: 'contemporary',
      definition:
        'Living or occurring at the same time; belonging to the same time',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_33',
      word: 'contradiction',
      definition:
        'A combination of statements, ideas, or features which are opposed to one another',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_34',
      word: 'controversial',
      definition:
        'Giving rise or likely to give rise to controversy or public disagreement',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_35',
      word: 'convenience',
      definition:
        'The state of being able to proceed with something without difficulty',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_36',
      word: 'conviction',
      definition:
        'A firmly held belief or opinion; the quality of showing that one is firmly convinced of what one believes or says',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_37',
      word: 'cooperative',
      definition: 'Involving mutual assistance in working toward a common goal',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_38',
      word: 'deliberate',
      definition: 'Done consciously and intentionally; careful and unhurried',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_39',
      word: 'demonstrate',
      definition:
        'To clearly show the existence or truth of something by giving proof or evidence',
      difficulty: 'B2',
      level: 'B2',
    },
    {
      id: 'b2_40',
      word: 'desperate',
      definition:
        'Feeling, showing, or involving a hopeless sense that a situation is so bad as to be impossible to deal with',
      difficulty: 'B2',
      level: 'B2',
    },
  ],
};
